const cards = {
    herz: {
        'ass': require('../img/cards/herz-ass.png'),
        'bube': require('../img/cards/herz-bube.png'),
        'dame': require('../img/cards/herz-dame.png'),
        'koenig': require('../img/cards/herz-koenig.png'),
        '2': require('../img/cards/herz2.png'),
        '3': require('../img/cards/herz3.png'),
        '4': require('../img/cards/herz4.png'),
        '5': require('../img/cards/herz5.png'),
        '6': require('../img/cards/herz6.png'),
        '7': require('../img/cards/herz7.png'),
        '8': require('../img/cards/herz8.png'),
        '9': require('../img/cards/herz9.png'),
        '10': require('../img/cards/herz10.png'),
    },
    kreuz: {
        'ass': require('../img/cards/kreuz-ass.png'),
        'bube': require('../img/cards/kreuz-bube.png'),
        'dame': require('../img/cards/kreuz-dame.png'),
        'koenig': require('../img/cards/kreuz-koenig.png'),
        '2': require('../img/cards/kreuz2.png'),
        '3': require('../img/cards/kreuz3.png'),
        '4': require('../img/cards/kreuz4.png'),
        '5': require('../img/cards/kreuz5.png'),
        '6': require('../img/cards/kreuz6.png'),
        '7': require('../img/cards/kreuz7.png'),
        '8': require('../img/cards/kreuz8.png'),
        '9': require('../img/cards/kreuz9.png'),
        '10': require('../img/cards/kreuz10.png'),
    },
    karo: {
        'ass': require('../img/cards/karo-ass.png'),
        'bube': require('../img/cards/karo-bube.png'),
        'dame': require('../img/cards/karo-dame.png'),
        'koenig': require('../img/cards/karo-koenig.png'),
        '2': require('../img/cards/karo2.png'),
        '3': require('../img/cards/karo3.png'),
        '4': require('../img/cards/karo4.png'),
        '5': require('../img/cards/karo5.png'),
        '6': require('../img/cards/karo6.png'),
        '7': require('../img/cards/karo7.png'),
        '8': require('../img/cards/karo8.png'),
        '9': require('../img/cards/karo9.png'),
        '10': require('../img/cards/karo10.png'),
    },
    pik: {
        'ass': require('../img/cards/pik-ass.png'),
        'bube': require('../img/cards/pik-bube.png'),
        'dame': require('../img/cards/pik-dame.png'),
        'koenig': require('../img/cards/pik-koenig.png'),
        '2': require('../img/cards/pik2.png'),
        '3': require('../img/cards/pik3.png'),
        '4': require('../img/cards/pik4.png'),
        '5': require('../img/cards/pik5.png'),
        '6': require('../img/cards/pik6.png'),
        '7': require('../img/cards/pik7.png'),
        '8': require('../img/cards/pik8.png'),
        '9': require('../img/cards/pik9.png'),
        '10': require('../img/cards/pik10.png'),
    }
};

export default cards;
