const cards = {
    'herz': {
        'ass': 'img/cards/herz-ass.png',
        'bube': 'img/cards/herz-bube.png',
        'dame': 'img/cards/herz-dame.png',
        'koenig': 'img/cards/herz-koenig.png',
        '2': 'img/cards/herz2.png',
        '3': 'img/cards/herz3.png',
        '4': 'img/cards/herz4.png',
        '5': 'img/cards/herz5.png',
        '6': 'img/cards/herz6.png',
        '7': 'img/cards/herz7.png',
        '8': 'img/cards/herz8.png',
        '9': 'img/cards/herz9.png',
        '10': 'img/cards/herz10.png',
    },
    'kreuz': {
        'ass': 'img/cards/kreuz-ass.png',
        'bube': 'img/cards/kreuz-bube.png',
        'dame': 'img/cards/kreuz-dame.png',
        'koenig': 'img/cards/kreuz-koenig.png',
        '2': 'img/cards/kreuz2.png',
        '3': 'img/cards/kreuz3.png',
        '4': 'img/cards/kreuz4.png',
        '5': 'img/cards/kreuz5.png',
        '6': 'img/cards/kreuz6.png',
        '7': 'img/cards/kreuz7.png',
        '8': 'img/cards/kreuz8.png',
        '9': 'img/cards/kreuz9.png',
        '10': 'img/cards/kreuz10.png',
    },
    'karo': {
        'ass': 'img/cards/karo-ass.png',
        'bube': 'img/cards/karo-bube.png',
        'dame': 'img/cards/karo-dame.png',
        'koenig': 'img/cards/karo-koenig.png',
        '2': 'img/cards/karo2.png',
        '3': 'img/cards/karo3.png',
        '4': 'img/cards/karo4.png',
        '5': 'img/cards/karo5.png',
        '6': 'img/cards/karo6.png',
        '7': 'img/cards/karo7.png',
        '8': 'img/cards/karo8.png',
        '9': 'img/cards/karo9.png',
        '10': 'img/cards/karo10.png',
    },
    'pik': {
        'ass': 'img/cards/pik-ass.png',
        'bube': 'img/cards/pik-bube.png',
        'dame': 'img/cards/pik-dame.png',
        'koenig': 'img/cards/pik-koenig.png',
        '2': 'img/cards/pik2.png',
        '3': 'img/cards/pik3.png',
        '4': 'img/cards/pik4.png',
        '5': 'img/cards/pik5.png',
        '6': 'img/cards/pik6.png',
        '7': 'img/cards/pik7.png',
        '8': 'img/cards/pik8.png',
        '9': 'img/cards/pik9.png',
        '10': 'img/cards/pik10.png',
    }
};

export default cards;
